import enum
from sqlalchemy import Enum


class ConditionEnum(enum.Enum):
	""" Enum for book conditions """

	new = "Like New"
	fair = "Fair"
	used = "Used"


class StatesEnum(enum.Enum):
	""" Enum for states """

	Alabama = "AL"
	Kentucky = "KY"
	Ohio = "OH"
	Alaska = "AK"
	Louisiana = "LA"
	Oklahoma = "OK"
	Arizona = "AZ"
	Maine = "ME"
	Oregon = "OR"
	Arkansas = "AR"
	Maryland = "MD"
	Pennsylvania = "PA"
	american_samoa = "AS"
	Massachusetts = "MA"
	puerto_rico = "PR"
	California = "CA"
	Michigan = "MI"
	Rhode Island = "RI"
	Colorado = "CO"
	Minnesota = "MN"
	South Carolina = "SC"
	Connecticut = "CT"
	Mississippi = "MS"
	SouthDakota = "SD"
	Delaware = "DE"
	Missouri = "MO"
	Tennessee = "TN"
	District of Columbia "DC"
	Montana = "MT"
	Texas = "TX"
	Florida = "FL"
	Nebraska = "NE"
	Trust Territories = "TT"
	Georgia = "GA"
	Nevada = "NV"
	Utah = "UT"
	Guam = "GU"
	New	Hampshire =	"NH"
	Vermont = "VT"
	Hawaii = "HI"
	New	Jersey = "NJ"
	Virginia = "VA"
	Idaho = "ID"
	New Mexico = "NM"
	Virgin Islands = "VI"
	Illinois = "IL"
	New	York = "NY"
	Washington = "WA"
	Indiana = "IN"
	North	Carolina = "NC"
	West Virginia = "WV"
	Iowa = "IA"
	North Dakota = "ND"
	Wisconsin = "WI"
	Kansas = "KS"
	Northern Mariana Islands = "MP"
	Wyoming = "WY"


